data:
  evfile : /nfs/slac/g/ki/ki20/cta/mdwood/fermi/data/P8_P302_BASE/P8_P302_SOURCE_239557414_528835414_ft1.lst
  scfile : /nfs/slac/g/ki/ki20/cta/mdwood/fermi/data/P8_P302_BASE/P8_P302_SOURCE_239557414_528835414_ft2.fits
  ltcube : /u/gl/afrancko/ki-disk2/blazars/ltcube_9years.fits

binning:
  roiwidth   : 10.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 100
  emax : 1000000 #316227.76
  zmax    : 90
  evclass : 128
  evtype  : 3
  tmin    : 239557417
  tmax    : 528835414
  filter  : null
  target : '3FGL J0509.4+0541'

gtlike:
  edisp : True
  irfs : 'P8R2_SOURCE_V6'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 15.0
  #galdiff: /afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/gll_iem_v06.fits 
  #isodiff: /afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/iso_P8R2_SOURCE_V6_v06.txt
  galdiff: /u/gl/mdwood/fermi/diffuse/gll_iem_ext_v06.fits
  isodiff: /nfs/farm/g/glast/u/buson/diffuse/myEXT_iso_P8R2_SOURCE_V6_v06.txt
  catalogs : ['3FGL']

lightcurve:
  multithread : True

#fileio:
#   outdir : null
#   logfile : null
#   usescratch : True
#   outdir_regex : ['\.xml$|\.npy$|\.yaml$|\.png$']
#   scratchdir  : '/scratch'
